# Pytorch Fundamentals

In [126]:
import torch
import torch.nn as nn # to define the network (layers etc.)
import torch.nn.functional as F # to add activation, pooling etc.
import torch.optim as optim # for optimizer
from torchvision import datasets, transforms # for datasets, augemntation etc.
from torchsummary import summary

In [127]:
# Define model
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=3, bias=True)
        #self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 12, 3)
        self.fc1 = nn.Linear(in_features=12 * 4 * 4, out_features=100)
        self.fc2 = nn.Linear(100, 32)
        self.fc3 = nn.Linear(32, 10, bias=True) # bias=True is optional

    def forward(self, x):
        # x = x # for input layer
        # x = self.pool(F.relu(self.conv1(x)))
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, kernel_size=2, stride=2)
        x = F.relu(self.conv2(x))
        # x = x.view(-1, 12 * 4 * 4)
        x.reshape(-1, 12*4*4)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

In [128]:
# Initialize model
model = MyModel()
model

MyModel(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=100, bias=True)
  (fc2): Linear(in_features=100, out_features=32, bias=True)
  (fc3): Linear(in_features=32, out_features=10, bias=True)
)

In [129]:
#summary(model, (1, 20, 20))

In [130]:
# Display first convolution layer details
print("Layer detail: ", model.conv1)

# display shappe of first convolution layer weights
print("Shape:",model.conv1.weight.shape)

# display weight of first convolution layer
print("\n \n Layer weights")
model.conv1.weight

Layer detail:  Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
Shape: torch.Size([6, 1, 3, 3])

 
 Layer weights


Parameter containing:
tensor([[[[ 0.0047,  0.1075,  0.1545],
          [-0.2406, -0.2451,  0.1067],
          [-0.0993, -0.0615, -0.0735]]],


        [[[ 0.1530,  0.0288,  0.2291],
          [-0.1787,  0.1892, -0.1219],
          [ 0.3188,  0.2594, -0.0242]]],


        [[[-0.0616,  0.2238,  0.0080],
          [-0.0592,  0.1425,  0.2551],
          [ 0.1240, -0.1726,  0.1480]]],


        [[[ 0.0777, -0.0052, -0.2027],
          [ 0.1458, -0.3095, -0.0811],
          [ 0.0433,  0.1471, -0.3007]]],


        [[[ 0.2475,  0.1249, -0.0577],
          [ 0.1488, -0.1611, -0.2106],
          [-0.2750, -0.3112,  0.1323]]],


        [[[-0.2730,  0.0687, -0.1748],
          [ 0.2167,  0.0216, -0.1394],
          [-0.3249, -0.0956, -0.3069]]]], requires_grad=True)

In [131]:
# Display first linear layer details
print("Layer detail:", model.fc1)

# display shappe of first linear layer weights
print("Shape: ", model.fc1.weight.shape)

# display weight of first linear layer
print("\n \n Weight")
model.fc1.weight

Layer detail: Linear(in_features=192, out_features=100, bias=True)
Shape:  torch.Size([100, 192])

 
 Weight


Parameter containing:
tensor([[-0.0227,  0.0692, -0.0220,  ..., -0.0174, -0.0690,  0.0028],
        [-0.0563,  0.0431,  0.0607,  ..., -0.0538, -0.0046,  0.0290],
        [-0.0495,  0.0691, -0.0441,  ..., -0.0364,  0.0357,  0.0292],
        ...,
        [-0.0156, -0.0173,  0.0203,  ...,  0.0098,  0.0604,  0.0644],
        [-0.0711, -0.0610, -0.0558,  ..., -0.0393, -0.0579,  0.0612],
        [-0.0261,  0.0294,  0.0258,  ..., -0.0654,  0.0432,  0.0402]],
       requires_grad=True)

In [132]:
# display first convolution layer bias
print("Convolution layer bias:", model.conv1.bias)

# display first linear layer bias
print("Linear layer bias:")
model.fc1.bias

Convolution layer bias: Parameter containing:
tensor([-0.1655, -0.2316,  0.0538, -0.0422,  0.2167,  0.0493],
       requires_grad=True)
Linear layer bias:


Parameter containing:
tensor([ 0.0694, -0.0496,  0.0164,  0.0662, -0.0111,  0.0032, -0.0292,  0.0163,
         0.0421, -0.0230, -0.0689, -0.0548, -0.0502, -0.0484, -0.0490,  0.0491,
        -0.0604, -0.0118,  0.0476, -0.0653,  0.0176, -0.0388,  0.0304,  0.0524,
        -0.0471, -0.0609,  0.0412,  0.0518, -0.0622,  0.0571, -0.0501, -0.0207,
         0.0644, -0.0192, -0.0604,  0.0279, -0.0209,  0.0528,  0.0653,  0.0668,
        -0.0328, -0.0293,  0.0517, -0.0069,  0.0530,  0.0355, -0.0479, -0.0429,
         0.0385,  0.0035,  0.0385,  0.0008,  0.0545, -0.0687,  0.0091,  0.0561,
         0.0213, -0.0386, -0.0416,  0.0181, -0.0004,  0.0591, -0.0494,  0.0644,
        -0.0707,  0.0488, -0.0011, -0.0518,  0.0182,  0.0243,  0.0172,  0.0103,
         0.0569, -0.0260, -0.0463, -0.0176, -0.0067,  0.0606, -0.0518, -0.0131,
        -0.0189,  0.0380, -0.0308,  0.0649,  0.0676, -0.0177,  0.0188,  0.0490,
        -0.0416, -0.0508,  0.0520, -0.0218,  0.0083,  0.0124, -0.0353,  0.0221,
        -0.0041,  

In [133]:
# Initialize optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

# Print model's state_dict
print("Model's state_dict:")
for param_tensor in model.state_dict():
    print(param_tensor, "\t", model.state_dict()[param_tensor].size())

# Print optimizer's state_dict
print("\n Optimizer's state_dict:")
for var_name in optimizer.state_dict():
    print(var_name, "\t", optimizer.state_dict()[var_name])

Model's state_dict:
conv1.weight 	 torch.Size([6, 1, 3, 3])
conv1.bias 	 torch.Size([6])
conv2.weight 	 torch.Size([12, 6, 3, 3])
conv2.bias 	 torch.Size([12])
fc1.weight 	 torch.Size([100, 192])
fc1.bias 	 torch.Size([100])
fc2.weight 	 torch.Size([32, 100])
fc2.bias 	 torch.Size([32])
fc3.weight 	 torch.Size([10, 32])
fc3.bias 	 torch.Size([10])

 Optimizer's state_dict:
state 	 {}
param_groups 	 [{'lr': 0.001, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'params': [2096015367768, 2096015367912, 2096015366256, 2096015365752, 2096015365248, 2096015367840, 2096015366184, 2096015366976, 2096015366832, 2096015366904]}]


In [134]:
for module in model.modules():
    print("dsa")
    print(module)

dsa
MyModel(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=100, bias=True)
  (fc2): Linear(in_features=100, out_features=32, bias=True)
  (fc3): Linear(in_features=32, out_features=10, bias=True)
)
dsa
Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
dsa
Conv2d(6, 12, kernel_size=(3, 3), stride=(1, 1))
dsa
Linear(in_features=192, out_features=100, bias=True)
dsa
Linear(in_features=100, out_features=32, bias=True)
dsa
Linear(in_features=32, out_features=10, bias=True)


# display each layer weight and bias shape details

In [135]:
# display each layer weight and bias shape details
for name, param in model.named_parameters():
    print(name, param.size())

conv1.weight torch.Size([6, 1, 3, 3])
conv1.bias torch.Size([6])
conv2.weight torch.Size([12, 6, 3, 3])
conv2.bias torch.Size([12])
fc1.weight torch.Size([100, 192])
fc1.bias torch.Size([100])
fc2.weight torch.Size([32, 100])
fc2.bias torch.Size([32])
fc3.weight torch.Size([10, 32])
fc3.bias torch.Size([10])


# display each layer weight and bias

In [136]:
count=1
for param in model.parameters():
    print("Layer", count)
    print(param)
    count+=1

Layer 1
Parameter containing:
tensor([[[[ 0.0047,  0.1075,  0.1545],
          [-0.2406, -0.2451,  0.1067],
          [-0.0993, -0.0615, -0.0735]]],


        [[[ 0.1530,  0.0288,  0.2291],
          [-0.1787,  0.1892, -0.1219],
          [ 0.3188,  0.2594, -0.0242]]],


        [[[-0.0616,  0.2238,  0.0080],
          [-0.0592,  0.1425,  0.2551],
          [ 0.1240, -0.1726,  0.1480]]],


        [[[ 0.0777, -0.0052, -0.2027],
          [ 0.1458, -0.3095, -0.0811],
          [ 0.0433,  0.1471, -0.3007]]],


        [[[ 0.2475,  0.1249, -0.0577],
          [ 0.1488, -0.1611, -0.2106],
          [-0.2750, -0.3112,  0.1323]]],


        [[[-0.2730,  0.0687, -0.1748],
          [ 0.2167,  0.0216, -0.1394],
          [-0.3249, -0.0956, -0.3069]]]], requires_grad=True)
Layer 2
Parameter containing:
tensor([-0.1655, -0.2316,  0.0538, -0.0422,  0.2167,  0.0493],
       requires_grad=True)
Layer 3
Parameter containing:
tensor([[[[-0.0190,  0.0096, -0.0551],
          [-0.1107,  0.0403,  0.1251

# Print weight and biases of specific/all layers

In [137]:
l=[]
for layer in model.children():
    weights = list(layer.parameters())
    l.append(weights)
print(l[0]) # change layer index (0-4) 
# above print line will display weights (6 filters) and biases (6) of first convolution layer

[Parameter containing:
tensor([[[[ 0.0047,  0.1075,  0.1545],
          [-0.2406, -0.2451,  0.1067],
          [-0.0993, -0.0615, -0.0735]]],


        [[[ 0.1530,  0.0288,  0.2291],
          [-0.1787,  0.1892, -0.1219],
          [ 0.3188,  0.2594, -0.0242]]],


        [[[-0.0616,  0.2238,  0.0080],
          [-0.0592,  0.1425,  0.2551],
          [ 0.1240, -0.1726,  0.1480]]],


        [[[ 0.0777, -0.0052, -0.2027],
          [ 0.1458, -0.3095, -0.0811],
          [ 0.0433,  0.1471, -0.3007]]],


        [[[ 0.2475,  0.1249, -0.0577],
          [ 0.1488, -0.1611, -0.2106],
          [-0.2750, -0.3112,  0.1323]]],


        [[[-0.2730,  0.0687, -0.1748],
          [ 0.2167,  0.0216, -0.1394],
          [-0.3249, -0.0956, -0.3069]]]], requires_grad=True), Parameter containing:
tensor([-0.1655, -0.2316,  0.0538, -0.0422,  0.2167,  0.0493],
       requires_grad=True)]
